[tool.poetry]
name = "ghostpost"
version = "0.1.0"
description = ""
authors = ["Ally Engle <allyson.engle@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
